# Generated by Django 2.0.5 on 2018-05-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('bISBN', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('bTitle', models.CharField(max_length=128, null=True)),
                ('bAuthor', models.CharField(max_length=128)),
                ('bPrice', models.FloatField()),
            ],
        ),
    ]
